name: Deploy Aristos

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: aristos-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: https://github.com/actions/checkout@v4

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@v31

      - name: Deploy
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          TARGET_HOST: root@144.202.31.40
        run: nix run github:thebrandonlucas/kai/9b9fcfc79932a5df50fa577379d7ad4acd77883c -- workflow deploy
