app [main!] { pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.22.2/9zUBxb1LtXYVc4eR4hAtd1WQDwBYDhM6HQdZz1UFCm2m.tar.zst" }

import pf.OsStr
import pf.Path
import pf.Stderr
import pf.Stdout

# Embeds the FSRS reference fixtures (tests/fixtures/fsrs/*.json) in the Elm
# test module tests/FsrsFixtures.elm, because elm-test cannot read files.
main! : List(OsStr) => Try({}, _)
main! = |_args| {
	match generate!({}) {
		Ok({}) => {
			Stdout.line!("Wrote ${output_path}")?
			Ok({})
		}
		Err(_) => {
			Stderr.line!("Could not generate ${output_path} from tests/fixtures/fsrs/.")?
			Err(Exit(1))
		}
	}
}

output_path = "tests/FsrsFixtures.elm"

generate! = |{}| {
	ts_fsrs = Path.read_utf8!(Path.utf8("tests/fixtures/fsrs/ts-fsrs.json"))?
	fsrs_rs = Path.read_utf8!(Path.utf8("tests/fixtures/fsrs/fsrs-rs.json"))?
	math_exp = Path.read_utf8!(Path.utf8("tests/fixtures/fsrs/math-exp.json"))?
	sections = [
		header,
		elm_string("tsFsrs", ts_fsrs),
		elm_string("fsrsRs", fsrs_rs),
		elm_string("mathExp", math_exp),
	]
	Path.write_utf8!(Path.utf8(output_path), Str.join_with(sections, "\n\n"))
}

header =
	\\module FsrsFixtures exposing (fsrsRs, mathExp, tsFsrs)
	\\
	\\{-| Generated by devtools/generate-fsrs-fixtures.roc from
	\\tests/fixtures/fsrs/*.json. Do not edit; run `kai workflow test-fsrs`.
	\\-}

# The fixtures are minified JSON on one line, so a triple-quoted Elm string
# only needs backslashes escaped.
elm_string = |name, json| {
	escaped = json.trim().replace_each("\\", "\\\\")
	"${name} : String\n${name} =\n    \"\"\"${escaped}\"\"\"\n"
}
