app [main!] {
    cli: platform "https://github.com/roc-lang/basic-cli/releases/download/0.20.0/X73hGh05nNTkDHU06FHC0YfFaQB1pimX7gncRcao5mU.tar.br"
}

import cli.File
import cli.Stdout

source_path = "conllu/xenophon/anabasis/book-01-first-sentence.tb.conllu"
output_path = "anabasis-data.js"
source_url = "https://github.com/lyceum-quest/conllu-viz"

main! = \_args ->
    result = run_import! {}

    when result is
        Ok {} -> Ok {}
        Err _ -> Err (Exit 1 "Anabasis import failed; inspect the CoNLL-U fixture and Roc diagnostics.")

run_import! = \{} ->
    content = File.read_utf8!(source_path)?
    payload = build_payload(content)?
    header = "// Generated by scripts/import-lyceum-anabasis.roc from $(source_path)\n"
    _ = File.write_utf8!("$(header)window.ARISTOS_DATA=$(payload);\n", output_path)?
    Stdout.line! "wrote $(output_path): 1 sentence, 15 tokens"

build_payload = \content ->
    lines = Str.split_on content "\n"
    rows = parse_rows(lines)?

    if List.len rows != 15 then
        Err (ExpectedTokenCount (List.len rows))
    else if List.len (List.keep_if rows \row -> row.head == "0") != 1 then
        Err InvalidRootCount
    else
        first = first_row(rows)?
        reference = misc_value first.misc "Ref"
        refs_match = List.all rows \row -> misc_value row.misc "Ref" == reference
        literal = metadata_value lines "literal_translation"
        prose = metadata_value lines "prose_translation"

        if reference == "" then
            Err MissingReference
        else if !(refs_match) then
            Err MixedReferences
        else if literal == "" || prose == "" then
            Err MissingTranslations
        else
            tokens = make_tokens rows
            chapter = first_part reference
            sentence_id = metadata_value lines "sentence_id"
            citation = metadata_value lines "cts_urn"
            stable_id = if citation == "" then "anabasis-$(reference)-s$(sentence_id)" else "$(citation)-s$(sentence_id)"
            source_name = metadata_or lines "project" "Lyceum Digital Library"
            edition = metadata_value lines "source_edition"
            license = metadata_value lines "license"
            revision = metadata_value lines "source_revision"
            sentence_text = reconstruct_text tokens
            token_json = Str.join_with (List.map tokens token_to_json) ","
            source_json = "{\"name\":$(json_string source_name),\"url\":$(json_string source_url),\"commit\":$(json_string revision),\"license\":$(json_string license),\"edition\":$(json_string edition)}"
            sentence_json = "{\"i\":$(json_string stable_id),\"c\":$(chapter),\"v\":$(json_string reference),\"x\":$(json_string sentence_text),\"d\":$(json_string literal),\"e\":$(json_string prose),\"t\":[$(token_json)]}"
            Ok "{\"source\":$(source_json),\"sentences\":[$(sentence_json)]}"

parse_rows = \lines ->
    when lines is
        [] -> Ok []
        [line, .. as rest] ->
            remaining = parse_rows(rest)?

            if line == "" || Str.starts_with line "#" then
                Ok remaining
            else
                row = parse_row(line)?
                Ok (List.prepend remaining row)

parse_row = \line ->
    when Str.split_on line "\t" is
        [id, form, lemma, upos, xpos, feats, head, relation, deps, misc] ->
            when (Str.to_u64 id, Str.to_u64 head) is
                (Ok _, Ok _) -> Ok { id, form, lemma, upos, xpos, feats, head, relation, deps, misc }
                _ -> Err (InvalidNumericColumn line)

        columns -> Err (InvalidColumnCount (List.len columns))

first_row = \rows ->
    when rows is
        [row, ..] -> Ok row
        [] -> Err MissingRows

make_tokens = \rows ->
    when rows is
        [] -> []
        [row] -> [make_token row ""]
        [row, next, .. as rest] -> List.prepend (make_tokens (List.prepend rest next)) (make_token row next.upos)

make_token = \row, next_upos ->
    features = if row.feats == "_" then "" else row.feats
    space_after = misc_value row.misc "SpaceAfter" != "No" && next_upos != "PUNCT"
    gloss = if row.upos == "PUNCT" then "" else metadata_pair_value row.misc ["Gloss", "gloss"]

    {
        id: row.id,
        form: row.form,
        lemma: row.lemma,
        upos: row.upos,
        morphology: features,
        case: field_value features "Case",
        number: field_value features "Number",
        gender: field_value features "Gender",
        head: row.head,
        relation: row.relation,
        gloss,
        space_after,
    }

token_to_json = \token ->
    spacing = if token.space_after then "true" else "false"
    "{\"i\":$(token.id),\"f\":$(json_string token.form),\"l\":$(json_string token.lemma),\"p\":$(json_string token.upos),\"m\":$(json_string token.morphology),\"c\":$(json_string token.case),\"n\":$(json_string token.number),\"g\":$(json_string token.gender),\"h\":$(token.head),\"r\":$(json_string token.relation),\"s\":$(json_string token.gloss),\"a\":$(spacing)}"

reconstruct_text = \tokens ->
    tokens
    |> List.map \token -> if token.space_after then "$(token.form) " else token.form
    |> Str.join_with ""
    |> Str.trim

metadata_value = \lines, key ->
    prefix = "# $(key) = "

    when List.keep_if lines \line -> Str.starts_with line prefix is
        [line, ..] -> Str.replace_first line prefix ""
        [] -> ""

metadata_or = \lines, key, fallback ->
    value = metadata_value lines key
    if value == "" then fallback else value

metadata_pair_value = \serialized, keys ->
    when keys is
        [] -> ""
        [key, .. as rest] ->
            value = field_value serialized key
            if value == "" then metadata_pair_value serialized rest else value

misc_value = \serialized, key -> field_value serialized key

field_value = \serialized, key ->
    prefix = "$(key)="

    when List.keep_if (Str.split_on serialized "|") \item -> Str.starts_with item prefix is
        [item, ..] -> Str.replace_first item prefix ""
        [] -> ""

first_part = \reference ->
    when Str.split_on reference "." is
        [part, ..] -> part
        [] -> "1"

json_string = \value ->
    escaped =
        value
        |> Str.replace_each "\\" "\\\\"
        |> Str.replace_each "\"" "\\\""
        |> Str.replace_each "\n" "\\n"
        |> Str.replace_each "\r" "\\r"
        |> Str.replace_each "\t" "\\t"

    "\"$(escaped)\""
