#!/usr/bin/env python3
"""Build the browser fixture for Genesis from UD Ancient Greek PTNK CoNLL-U.

Usage:
    python scripts/import-ptnk-genesis.py /path/to/UD_Ancient_Greek-PTNK
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

SOURCE_COMMIT = "818fb315ff1f6cd95b6e7fa90f3707488d2b010d"
SOURCE_URL = "https://github.com/UniversalDependencies/UD_Ancient_Greek-PTNK"
OUTPUT = Path(__file__).resolve().parents[1] / "genesis-data.js"
SENTENCE_ID = re.compile(r"^Septuagint-Genesis-(\d+):(\d+(?:-\d+)?)-grc$")


def parse_misc(value: str) -> dict[str, str]:
    if value == "_":
        return {}
    result: dict[str, str] = {}
    for item in value.split("|"):
        key, separator, item_value = item.partition("=")
        if separator:
            result[key] = item_value
    return result


def parse_features(value: str) -> dict[str, str]:
    if value == "_":
        return {}
    return dict(item.split("=", 1) for item in value.split("|") if "=" in item)


def parse_file(path: Path) -> list[dict]:
    sentences: list[dict] = []
    metadata: dict[str, str] = {}
    tokens: list[dict] = []

    def finish_sentence() -> None:
        nonlocal metadata, tokens
        sentence_id = metadata.get("sent_id", "")
        match = SENTENCE_ID.match(sentence_id)
        if match and tokens:
            sentences.append(
                {
                    "i": sentence_id,
                    "c": int(match.group(1)),
                    "v": match.group(2),
                    "x": metadata.get("text", ""),
                    "t": tokens,
                }
            )
        metadata = {}
        tokens = []

    for raw_line in path.read_text(encoding="utf-8").splitlines() + [""]:
        line = raw_line.strip("\n")
        if not line:
            finish_sentence()
            continue
        if line.startswith("# "):
            key, separator, value = line[2:].partition(" = ")
            if separator:
                metadata[key] = value
            continue
        if not SENTENCE_ID.match(metadata.get("sent_id", "")):
            continue

        columns = line.split("\t")
        if len(columns) != 10 or not columns[0].isdigit():
            continue
        features = parse_features(columns[5])
        misc = parse_misc(columns[9])
        tokens.append(
            {
                "i": int(columns[0]),
                "f": columns[1],
                "l": columns[2],
                "p": columns[3],
                "m": columns[5] if columns[5] != "_" else "",
                "c": features.get("Case", ""),
                "n": features.get("Number", ""),
                "g": features.get("Gender", ""),
                "h": int(columns[6]),
                "r": columns[7],
                "s": misc.get("Gloss", ""),
                "a": misc.get("SpaceAfter") != "No",
            }
        )

    return sentences


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: import-ptnk-genesis.py PATH_TO_UD_REPOSITORY")

    source = Path(sys.argv[1]).resolve()
    source_commit = subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if source_commit != SOURCE_COMMIT:
        raise SystemExit(
            f"expected PTNK commit {SOURCE_COMMIT}, found {source_commit}; review and update the pinned importer first"
        )

    files = sorted(source.glob("grc_ptnk-ud-*.conllu"))
    if len(files) != 3:
        raise SystemExit(f"expected three PTNK split files in {source}, found {len(files)}")

    sentences = [sentence for path in files for sentence in parse_file(path)]
    sentences.sort(
        key=lambda sentence: (sentence["c"], int(sentence["v"].split("-", 1)[0]), sentence["i"])
    )

    chapters = {sentence["c"] for sentence in sentences}
    if chapters != set(range(1, 51)):
        raise SystemExit(f"expected Genesis chapters 1-50, found {sorted(chapters)}")
    if len(sentences) != 1491:
        raise SystemExit(f"expected 1491 Genesis sentences, found {len(sentences)}")

    payload = {
        "source": {
            "name": "UD Ancient Greek PTNK",
            "url": SOURCE_URL,
            "commit": SOURCE_COMMIT,
            "license": "CC BY-SA 4.0",
            "edition": "Septuagint according to Codex Alexandrinus",
        },
        "sentences": sentences,
    }
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    OUTPUT.write_text(
        "// Generated by scripts/import-ptnk-genesis.py; see data/ptnk/README.md\n"
        f"window.ARISTOS_DATA={encoded};\n",
        encoding="utf-8",
    )
    token_count = sum(len(sentence["t"]) for sentence in sentences)
    print(f"wrote {OUTPUT}: {len(sentences)} sentences, {token_count} tokens")


if __name__ == "__main__":
    main()
