import LyceumConllu

LyceumImportSql :: [].{

	Config : { input : Str, texts_db : Str, editions_db : Str, sql_output : Str, work_urn : Str, edition_slug : Str, generator : Str }

	quote = |text| "'${Str.replace_each(text, "'", "''")}'"

	build : Config, List(LyceumConllu.Verse) -> Str
	build = |config, verses| {
		greek_urn = "${config.work_urn}.${config.edition_slug}-grc1"
		english_urn = "${config.work_urn}.${config.edition_slug}-versified-eng1"
		marker = "Aristos generated edition; model=${config.generator}; not human-adjudicated"
		setup =
			\\PRAGMA foreign_keys = ON;
			\\BEGIN IMMEDIATE;
			\\CREATE TEMP TABLE _import_target(work_urn TEXT, greek_urn TEXT, english_urn TEXT, marker TEXT, generator TEXT);
			\\CREATE TEMP TABLE _import_verses(reference TEXT PRIMARY KEY, greek TEXT NOT NULL, prose TEXT NOT NULL);
			\\CREATE TEMP TABLE _import_words(reference TEXT, word_index INTEGER, greek TEXT, lemma TEXT, pos TEXT, morphology TEXT, gloss TEXT, transliteration TEXT, PRIMARY KEY(reference, word_index));
		catalog =
			\\INSERT INTO curated.authors(id, urn, name)
			\\SELECT a.id, a.urn, a.name FROM main.authors a JOIN main.works w ON w.author_id=a.id JOIN _import_target t ON t.work_urn=w.urn
			\\WHERE NOT EXISTS(SELECT 1 FROM curated.authors ca WHERE ca.urn=a.urn);
			\\INSERT INTO curated.works(id, author_id, urn, title, language)
			\\SELECT w.id, w.author_id, w.urn, w.title, w.language FROM main.works w JOIN _import_target t ON t.work_urn=w.urn
			\\WHERE NOT EXISTS(SELECT 1 FROM curated.works cw WHERE cw.urn=w.urn);
			\\INSERT INTO curated.editions(id, work_id, urn, label, description, language, type, parent_work_urn, is_lyceum_curated)
			\\SELECT e.id, e.work_id, e.urn, e.label, e.description, e.language, e.type, t.work_urn, 1
			\\FROM main.editions e JOIN _import_target t ON e.urn IN(t.greek_urn,t.english_urn)
			\\WHERE NOT EXISTS(SELECT 1 FROM curated.editions ce WHERE ce.urn=e.urn);
		Str.join_with(
			[
				"-- Generated by Aristos. Import into texts.db with sqlite3 -bail; attaches editions.db.\nATTACH DATABASE ${quote(config.editions_db)} AS curated;",
				setup,
				"INSERT INTO _import_target VALUES(${quote(config.work_urn)},${quote(greek_urn)},${quote(english_urn)},${quote(marker)},${quote(config.generator)});",
				Str.join_with(List.map(verses, verse_sql), "\n"),
				schema,
				guard("work_must_exist", "(SELECT COUNT(*) FROM main.works w JOIN main.authors a ON a.id=w.author_id JOIN _import_target t ON t.work_urn=w.urn)=1"),
				guard("catalog_ids_must_agree", catalog_agreement),
				guard("generated_editions_only", ownership),
				edition_sql("greek_urn", "grc", "edition", " (Aristos Greek)"),
				edition_sql("english_urn", "eng", "translation", " (Aristos verse-aligned English)"),
				guard("edition_ids_must_agree", edition_agreement),
				catalog,
				import_into("main"),
				import_into("curated"),
				"COMMIT;",
			],
			"\n\n",
		)
	}

	verse_sql = |verse| {
		row = "INSERT INTO _import_verses VALUES(${quote(verse.reference)},${quote(verse.greek)},${quote(verse.prose)});"
		"${row}\n${words_sql(verse.words, verse.reference, 0)}"
	}
	words_sql = |words, reference, index| match words {
		[] => ""
		[word, .. as rest] => {
			values = Str.join_with(List.map([reference, word.form, word.lemma, word.pos, word.morphology, word.gloss, word.transliteration], quote), ",")
			row = "INSERT INTO _import_words(reference,greek,lemma,pos,morphology,gloss,transliteration,word_index) VALUES(${values},${U64.to_str(index)});"
			"${row}\n${words_sql(rest, reference, index + 1)}"
		}
	}

	guard = |name, condition| "CREATE TEMP TABLE ${name}(ok INTEGER NOT NULL CONSTRAINT ${name} CHECK(ok=1));\nINSERT INTO ${name} VALUES(CASE WHEN ${condition} THEN 1 ELSE 0 END);"

	catalog_agreement =
		\\NOT EXISTS(
		\\ SELECT 1 FROM main.works w JOIN _import_target t ON t.work_urn=w.urn JOIN main.authors a ON a.id=w.author_id
		\\ JOIN curated.authors ca ON ca.id=a.id OR ca.urn=a.urn WHERE ca.id<>a.id OR ca.urn<>a.urn
		\\) AND NOT EXISTS(
		\\ SELECT 1 FROM main.works w JOIN _import_target t ON t.work_urn=w.urn
		\\ JOIN curated.works cw ON cw.id=w.id OR cw.urn=w.urn WHERE cw.id<>w.id OR cw.urn<>w.urn OR cw.author_id<>w.author_id
		\\)

	ownership =
		\\NOT EXISTS(
		\\ SELECT 1 FROM (SELECT work_id,urn,description,language,type FROM main.editions UNION ALL SELECT work_id,urn,description,language,type FROM curated.editions) e
		\\ JOIN _import_target t ON e.urn IN(t.greek_urn,t.english_urn) JOIN main.works w ON w.urn=t.work_urn
		\\ WHERE e.work_id<>w.id OR COALESCE(e.description,'')<>t.marker
		\\ OR (e.urn=t.greek_urn AND (e.language<>'grc' OR e.type<>'edition'))
		\\ OR (e.urn=t.english_urn AND (e.language<>'eng' OR e.type<>'translation'))
		\\)

	edition_agreement =
		\\NOT EXISTS(
		\\ SELECT 1 FROM main.editions e JOIN _import_target t ON e.urn IN(t.greek_urn,t.english_urn)
		\\ JOIN curated.editions ce ON ce.id=e.id OR ce.urn=e.urn WHERE ce.id<>e.id OR ce.urn<>e.urn
		\\)

	edition_sql = |key, language, kind, suffix| {
		# IDs are shared across databases because the reader falls back by bare numeric ID.
		prefix = "INSERT INTO main.editions(id,work_id,urn,label,description,language,type)"
		select = "SELECT COALESCE((SELECT id FROM curated.editions WHERE urn=t.${key}),(SELECT COALESCE(MAX(id),0)+1 FROM (SELECT id FROM main.editions UNION ALL SELECT id FROM curated.editions))),w.id,t.${key},w.title||${quote(suffix)},t.marker,${quote(language)},${quote(kind)}"
		"${prefix}\n${select}\nFROM main.works w JOIN _import_target t ON t.work_urn=w.urn WHERE NOT EXISTS(SELECT 1 FROM main.editions e WHERE e.urn=t.${key});"
	}

	import_into = |db| {
		# Replace only this importer-owned edition's supplied references; retain all other data.
		body =
			\\DELETE FROM DB.aligned_words WHERE segment_id IN(
			\\ SELECT s.id FROM DB.aligned_segments s JOIN _import_target t ON s.source_urn=t.greek_urn JOIN _import_verses v ON v.reference=s.reference
			\\);
			\\DELETE FROM DB.aligned_segments WHERE source_urn=(SELECT greek_urn FROM _import_target) AND reference IN(SELECT reference FROM _import_verses);
			\\DELETE FROM DB.segments WHERE edition_id IN(SELECT e.id FROM DB.editions e JOIN _import_target t ON e.urn IN(t.greek_urn,t.english_urn)) AND reference IN(SELECT reference FROM _import_verses);
			\\INSERT INTO DB.segments(edition_id,reference,content)
			\\SELECT e.id,v.reference,v.greek FROM _import_verses v CROSS JOIN _import_target t JOIN DB.editions e ON e.urn=t.greek_urn;
			\\INSERT INTO DB.segments(edition_id,reference,content)
			\\SELECT e.id,v.reference,v.prose FROM _import_verses v CROSS JOIN _import_target t JOIN DB.editions e ON e.urn=t.english_urn;
			\\INSERT INTO DB.aligned_segments(source_urn,translation_urn,reference,greek,transliteration,generated,generator)
			\\SELECT t.greek_urn,t.english_urn,v.reference,v.greek,'',v.prose,t.generator FROM _import_verses v CROSS JOIN _import_target t;
			\\INSERT INTO DB.aligned_words(segment_id,word_index,greek,transliteration,lemma,contextual_gloss,aligned_translation,pos,notes,morphology)
			\\SELECT s.id,w.word_index,w.greek,w.transliteration,w.lemma,w.gloss,'',w.pos,'',w.morphology
			\\FROM _import_words w JOIN DB.aligned_segments s ON s.reference=w.reference JOIN _import_target t ON s.source_urn=t.greek_urn;
		Str.replace_each(body, "DB.", "${db}.")
	}

	schema =
		\\CREATE TABLE IF NOT EXISTS curated.authors(id INTEGER PRIMARY KEY, urn TEXT NOT NULL UNIQUE, name TEXT NOT NULL);
		\\CREATE TABLE IF NOT EXISTS curated.works(id INTEGER PRIMARY KEY, author_id INTEGER NOT NULL REFERENCES authors(id), urn TEXT NOT NULL UNIQUE, title TEXT NOT NULL, language TEXT);
		\\CREATE TABLE IF NOT EXISTS curated.editions(id INTEGER PRIMARY KEY, work_id INTEGER NOT NULL REFERENCES works(id), urn TEXT NOT NULL UNIQUE, label TEXT, description TEXT, language TEXT NOT NULL, type TEXT NOT NULL, parent_work_urn TEXT, is_lyceum_curated BOOLEAN DEFAULT 0, parent_edition_id INTEGER REFERENCES editions(id));
		\\CREATE TABLE IF NOT EXISTS curated.segments(id INTEGER PRIMARY KEY, edition_id INTEGER NOT NULL REFERENCES editions(id), reference TEXT NOT NULL, content TEXT NOT NULL);
		\\CREATE TABLE IF NOT EXISTS curated.aligned_segments(id INTEGER PRIMARY KEY, source_urn TEXT NOT NULL, translation_urn TEXT NOT NULL, reference TEXT NOT NULL, greek TEXT NOT NULL, transliteration TEXT, generated TEXT, generator TEXT, UNIQUE(source_urn,reference));
		\\CREATE TABLE IF NOT EXISTS curated.aligned_words(id INTEGER PRIMARY KEY, segment_id INTEGER NOT NULL REFERENCES aligned_segments(id), word_index INTEGER NOT NULL, greek TEXT NOT NULL, transliteration TEXT, lemma TEXT, contextual_gloss TEXT, aligned_translation TEXT, pos TEXT, notes TEXT, morphology TEXT);
		\\CREATE TABLE IF NOT EXISTS curated.text_metadata(id INTEGER PRIMARY KEY, edition_urn TEXT, reference TEXT, title TEXT, word_count INTEGER, unique_lemma_count INTEGER, difficulty_stage INTEGER);
		\\CREATE INDEX IF NOT EXISTS curated.idx_aristos_segments_ref ON segments(edition_id,reference);
		\\CREATE INDEX IF NOT EXISTS curated.idx_aristos_words_segment ON aligned_words(segment_id,word_index);
		\\CREATE INDEX IF NOT EXISTS curated.idx_aristos_alignment_ref ON aligned_segments(source_urn,reference);
}
